version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lucky_wheel
        ports:
            - "8080:80"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        volumes:
            - .:/var/www/html
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
